// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Inter.Server.Data;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Inter.Server.Data
{
    public partial interface IMyGranddaddyContextProcedures
    {
        Task<List<FamilyTreeGetResult>> FamilyTreeGetAsync(string identityNumber, OutputParameter<int?> FatherCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<FamilyTreeRootGetResult>> FamilyTreeRootGetAsync(string identityNumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
